steps:
  # Step 1: SSH into VM and stop any running app
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        gcloud compute ssh ubuntu@tj-test \
          --zone=asia-south1-c \
          --command="bash ~/cloudbuild/stop.sh"

  # Step 2: SSH into VM and clone/update repo
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        gcloud compute ssh ubuntu@tj-test \
          --zone=asia-south1-c \
          --command="
            if [ ! -d ~/ae-manage ]; then
              git clone https://github.com/YOUR_USERNAME/YOUR_REPO.git ~/ae-manage
            else
              cd ~/ae-manage && git pull
            fi
          "

  # Step 3: SSH into VM and run component scripts
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        gcloud compute ssh ubuntu@tj-test \
          --zone=asia-south1-c \
          --command="bash ~/ae-manage/cloudbuild/component.sh"

  # Step 4: SSH into VM and start the app
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        gcloud compute ssh ubuntu@tj-test \
          --zone=asia-south1-c \
          --command="bash ~/ae-manage/cloudbuild/app_start.sh"

timeout: 1200s

options:
  logging: CLOUD_LOGGING_ONLY
