steps:
# Step 1: SSH into VM and stop running containers
- name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args:
    - -c
    - |
      gcloud compute ssh ubuntu@tj-test \
        --zone=asia-south1-c \
        --command="bash /home/ubuntu/stop.sh"

# Step 2: Clean old app directory
- name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args:
    - -c
    - |
      gcloud compute ssh ubuntu@tj-test \
        --zone=asia-south1-c \
        --command="bash /home/ubuntu/cleanup.sh"

# Step 3: Copy new code to VM
- name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args:
    - -c
    - |
      gcloud compute scp --recurse . ubuntu@tj-test:/home/ubuntu/ae-manage \
        --zone=asia-south1-c

# Step 4: Start app (pull config + docker-compose up)
- name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args:
    - -c
    - |
      gcloud compute ssh ubuntu@tj-test \
        --zone=asia-south1-c \
        --command="bash /home/ubuntu/ae-manage/app_start.sh"

timeout: 1200s
