steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - -c
      - |
        echo "Deploying to VM tj-test..."

        gcloud compute ssh ubuntu@tj-test \
          --zone=asia-south1-c \
          --command="
            set -e

            echo 'Cleaning old app directory'
            rm -rf /home/ubuntu/ae-manage

            echo 'Cloning repo'
            git clone https://github.com/Ashishd167/tj-testing.git /home/ubuntu/ae-manage

            cd /home/ubuntu/ae-manage/cloudbuild

            echo 'Stopping existing app'
            bash app_stop.sh || true
            echo 'Running before_install'
            bash before_install.sh

            cd /home/ubuntu
            echo 'Cloning  again repo'
            git clone https://github.com/Ashishd167/tj-testing.git /home/ubuntu/ae-manage

            echo 'Starting app'
            bash app_start.sh
          "
options:
  logging: CLOUD_LOGGING_ONLY
