steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        gcloud compute ssh ubuntu@tj-test \
          --zone=asia-south1-c \
          --command="
            if [ ! -d ~/ae-manage ]; then
              git clone https://github.com/Ashishd167/tj-testing.git ~/ae-manage
            else
              cd ~/ae-manage && git pull
            fi
          "

  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        gcloud compute ssh ubuntu@tj-test \
          --zone=asia-south1-c \
          --command="bash ~/ae-manage/cloudbuild/stop.sh"

  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        gcloud compute ssh ubuntu@tj-test \
          --zone=asia-south1-c \
          --command="bash ~/ae-manage/cloudbuild/clean.sh"

  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        gcloud compute ssh ubuntu@tj-test \
          --zone=asia-south1-c \
          --command="bash ~/ae-manage/cloudbuild/app_start.sh"

timeout: 1200s

options:
  logging: CLOUD_LOGGING_ONLY
