steps:
  # Step 1: SSH into VM and clone/update repo
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        gcloud compute ssh ubuntu@tj-test \
          --zone=asia-south1-c \
          --command="
            if [ ! -d ~/ae-manage ]; then
              git clone https://github.com/Ashishd167/tj-testing.git ~/ae-manage
            else
              cd ~/ae-manage && git pull
            fi
          "

  # Step 2: Run stop.sh from repo
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        gcloud compute ssh ubuntu@tj-test \
          --zone=asia-south1-c \
          --command="bash ~/ae-manage/codebuild/stop.sh"

  # Step 3: Run clean.sh from repo
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        gcloud compute ssh ubuntu@tj-test \
          --zone=asia-south1-c \
          --command="bash ~/ae-manage/codebuild/clean.sh"

  # Step 4: Run app_start.sh (Dockerfile build & run)
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        gcloud compute ssh ubuntu@tj-test \
          --zone=asia-south1-c \
          --command="bash ~/ae-manage/codebuild/app_start.sh"

timeout: 1200s

options:
  logging: CLOUD_LOGGING_ONLY
